language: perl

env:
  - PATH=/opt/rakudo/bin:/home/travis/.perl6/bin:$PATH

before_install:
  - wget https://github.com/nxadm/rakudo-pkg/releases/download/v2020.02.1-07/rakudo-pkg-Ubuntu16.04_2020.02.1-07_amd64.deb
  - sudo dpkg -i *.deb 

install:
    - zef install Bailador --force-test --/test

script:
  - zef install .

